// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZLMediaKitService.DataBase;

namespace ZLMediaKitService.Migrations
{
    [DbContext(typeof(ZLMediaKitContext))]
    partial class ZLMediaKitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ZLMediaKitService.DataBase.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnName("Account")
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<long>("CreateTime")
                        .HasColumnName("CREATE_TIME")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnName("Password")
                        .HasColumnType("TEXT");

                    b.Property<long>("SortId")
                        .HasColumnName("SORT_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnName("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdateTime")
                        .HasColumnName("UPDATE_TIME")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.HasIndex("SortId");

                    b.ToTable("Tb_User");
                });
#pragma warning restore 612, 618
        }
    }
}
